-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = "30일 이상"
WHERE C.CAR_TYPE IN ("SUV", "세단")
    AND C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) >= 500000
    AND C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) < 2000000
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE "2022-11-01" BETWEEN START_DATE AND END_DATE
            OR "2022-11-30" BETWEEN START_DATE AND END_DATE
    )
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC