-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * SUM(FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
LEFT JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE IS NOT NULL
    AND FO.PRODUCE_DATE LIKE '2022-05%'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC